# Generated by Django 4.2.7 on 2024-07-22 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_alter_admin_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
