# Generated by Django 5.0.7 on 2024-08-09 09:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0004_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='transaction_password',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('trade_no', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('utr', models.CharField(max_length=100, null=True, unique=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet_app.bankdetails')),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet_app.deposit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
