# Generated by Django 5.0.7 on 2024-08-12 13:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0006_withdrawal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='wallet_address',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Wallet address must be alphanumeric without spaces.', regex='^[a-zA-Z0-9]*$')]),
        ),
    ]
