# Generated by Django 5.0.7 on 2024-08-12 17:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0010_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='wallet_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
